site_name: Smusdi
theme:
  name: material
  logo: assets/images/smusdi-logo.png
  features:
    - navigation.expand
extra_css:
  - css/overrides.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - glightbox
  - include-markdown
nav:
  - index.md
  - Smusdi Web API:
    - webapi-config.md
